Document: dypgen
Title: Debian dypgen Manual
Author: <insert document author here>
Abstract: This manual describes what dypgen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dypgen/dypgen.sgml.gz

Format: postscript
Files: /usr/share/doc/dypgen/dypgen.ps.gz

Format: text
Files: /usr/share/doc/dypgen/dypgen.text.gz

Format: HTML
Index: /usr/share/doc/dypgen/html/index.html
Files: /usr/share/doc/dypgen/html/*.html
