# comment this line if you don't want to compile with ocamlopt
CAMLOPT=ocamlopt

# this is the path of OCaml standard library
OCAMLLIBDIR:=$(shell ocamlc -where)

# this is the path where you want to install the library of dypgen
DYPGENLIBDIR:=$(DESTDIR)$(OCAMLLIBDIR)

# this is the path where you want to install dypgen and dyp2gram.pl
BINDIR:=$(DESTDIR)/usr/bin

MANDIR:=$(DESTDIR)/usr/share/man/man1
