#!/bin/bash

sed -i "" s/JU_64BIT/JU_32BIT/g build/release/iOS/config/judy.fpc || exit 1

ARCH=armv7s
SDK=$(xcrun --sdk iphoneos --show-sdk-path)

export ARCH SDK
DYLD_LIBRARY_PATH=build/release/host/lib/rtl build/release/host/bin/flx_build_rtl  --debug --static --target-dir=build/release --target-bin=iOS --pkg=build_flx_rtl_clang_iphoneos

