#! /usr/bin/python2.4
#line 24 "./lpsrc/flx_felix_tangler.pak"

#--start constants--
ENDMARKER = 0
NAME = 1
NUMBER = 2
STRING = 3
NEWLINE = 4
INDENT = 5
DEDENT = 6
ERRORTOKEN = 7
OP = 8
#line 40 "./lpsrc/flx_felix_tangler.pak"
ALL = 9
#line 40 "./lpsrc/flx_felix_tangler.pak"
ASSERT = 10
#line 40 "./lpsrc/flx_felix_tangler.pak"
AXIOM = 11
#line 40 "./lpsrc/flx_felix_tangler.pak"
BODY = 12
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALL = 13
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASE = 14
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASENO = 15
#line 40 "./lpsrc/flx_felix_tangler.pak"
CLASS = 16
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMMENT_KEYWORD = 17
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMPOUND = 18
#line 40 "./lpsrc/flx_felix_tangler.pak"
CONST = 19
#line 40 "./lpsrc/flx_felix_tangler.pak"
CCLASS = 20
#line 40 "./lpsrc/flx_felix_tangler.pak"
CSTRUCT = 21
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTOR = 22
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTYPES = 23
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEF = 24
#line 40 "./lpsrc/flx_felix_tangler.pak"
DO = 25
#line 40 "./lpsrc/flx_felix_tangler.pak"
DONE = 26
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELIF = 27
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELSE = 28
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDCASE = 29
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDIF = 30
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDMATCH = 31
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENUM = 32
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPECT = 33
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPORT = 34
#line 40 "./lpsrc/flx_felix_tangler.pak"
FOR = 35
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORGET = 36
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORK = 37
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTOR = 38
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTION = 39
#line 40 "./lpsrc/flx_felix_tangler.pak"
GENERATOR = 40
#line 40 "./lpsrc/flx_felix_tangler.pak"
GOTO = 41
#line 40 "./lpsrc/flx_felix_tangler.pak"
HEADER = 42
#line 40 "./lpsrc/flx_felix_tangler.pak"
IDENT = 43
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCLUDE = 44
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCOMPLETE = 45
#line 40 "./lpsrc/flx_felix_tangler.pak"
INF = 46
#line 40 "./lpsrc/flx_felix_tangler.pak"
IN = 47
#line 40 "./lpsrc/flx_felix_tangler.pak"
IS = 48
#line 40 "./lpsrc/flx_felix_tangler.pak"
INHERIT = 49
#line 40 "./lpsrc/flx_felix_tangler.pak"
INLINE = 50
#line 40 "./lpsrc/flx_felix_tangler.pak"
JUMP = 51
#line 40 "./lpsrc/flx_felix_tangler.pak"
LET = 52
#line 40 "./lpsrc/flx_felix_tangler.pak"
LOOP = 53
#line 40 "./lpsrc/flx_felix_tangler.pak"
LVAL = 54
#line 40 "./lpsrc/flx_felix_tangler.pak"
MACRO = 55
#line 40 "./lpsrc/flx_felix_tangler.pak"
MODULE = 56
#line 40 "./lpsrc/flx_felix_tangler.pak"
NAN = 57
#line 40 "./lpsrc/flx_felix_tangler.pak"
NEW = 58
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOINLINE = 59
#line 40 "./lpsrc/flx_felix_tangler.pak"
NONTERM = 60
#line 40 "./lpsrc/flx_felix_tangler.pak"
NORETURN = 61
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOT = 62
#line 40 "./lpsrc/flx_felix_tangler.pak"
OBJECT = 63
#line 40 "./lpsrc/flx_felix_tangler.pak"
OPEN = 64
#line 40 "./lpsrc/flx_felix_tangler.pak"
PACKAGE = 65
#line 40 "./lpsrc/flx_felix_tangler.pak"
POD = 66
#line 40 "./lpsrc/flx_felix_tangler.pak"
PRIVATE = 67
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROCEDURE = 68
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROPERTY = 69
#line 40 "./lpsrc/flx_felix_tangler.pak"
REDUCE = 70
#line 40 "./lpsrc/flx_felix_tangler.pak"
REF = 71
#line 40 "./lpsrc/flx_felix_tangler.pak"
RENAME = 72
#line 40 "./lpsrc/flx_felix_tangler.pak"
REQUIRES = 73
#line 40 "./lpsrc/flx_felix_tangler.pak"
RETURN = 74
#line 40 "./lpsrc/flx_felix_tangler.pak"
STRUCT = 75
#line 40 "./lpsrc/flx_felix_tangler.pak"
THEN = 76
#line 40 "./lpsrc/flx_felix_tangler.pak"
TODO = 77
#line 40 "./lpsrc/flx_felix_tangler.pak"
TO = 78
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEDEF = 79
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPE = 80
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNION = 81
#line 40 "./lpsrc/flx_felix_tangler.pak"
USE = 82
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAL = 83
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAR = 84
#line 40 "./lpsrc/flx_felix_tangler.pak"
WHEN = 85
#line 40 "./lpsrc/flx_felix_tangler.pak"
WITH = 86
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_POINTER = 87
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_TYPE = 88
#line 40 "./lpsrc/flx_felix_tangler.pak"
SVC = 89
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEREF = 90
#line 40 "./lpsrc/flx_felix_tangler.pak"
AND = 91
#line 40 "./lpsrc/flx_felix_tangler.pak"
AS = 92
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALLBACK = 93
#line 40 "./lpsrc/flx_felix_tangler.pak"
CODE = 94
#line 40 "./lpsrc/flx_felix_tangler.pak"
IF = 95
#line 40 "./lpsrc/flx_felix_tangler.pak"
ISIN = 96
#line 40 "./lpsrc/flx_felix_tangler.pak"
MATCH = 97
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOEXPAND = 98
#line 40 "./lpsrc/flx_felix_tangler.pak"
OF = 99
#line 40 "./lpsrc/flx_felix_tangler.pak"
OR = 100
#line 40 "./lpsrc/flx_felix_tangler.pak"
PARSE = 101
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGEXP = 102
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGLEX = 103
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGMATCH = 104
#line 40 "./lpsrc/flx_felix_tangler.pak"
THE = 105
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEMATCH = 106
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPECASE = 107
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNDERSCORE = 108
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOLLAR = 109
#line 44 "./lpsrc/flx_felix_tangler.pak"
QUEST = 110
#line 44 "./lpsrc/flx_felix_tangler.pak"
EXCLAMATION = 111
#line 44 "./lpsrc/flx_felix_tangler.pak"
LPAR = 112
#line 44 "./lpsrc/flx_felix_tangler.pak"
RPAR = 113
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQB = 114
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQB = 115
#line 44 "./lpsrc/flx_felix_tangler.pak"
LBRACE = 116
#line 44 "./lpsrc/flx_felix_tangler.pak"
RBRACE = 117
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLON = 118
#line 44 "./lpsrc/flx_felix_tangler.pak"
COMMA = 119
#line 44 "./lpsrc/flx_felix_tangler.pak"
SEMI = 120
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUS = 121
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUS = 122
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAR = 123
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASH = 124
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAR = 125
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPER = 126
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESS = 127
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATER = 128
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQUAL = 129
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOT = 130
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENT = 131
#line 44 "./lpsrc/flx_felix_tangler.pak"
BACKQUOTE = 132
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDE = 133
#line 44 "./lpsrc/flx_felix_tangler.pak"
CIRCUMFLEX = 134
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASH = 135
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESS = 136
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATER = 137
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQEQUAL = 138
#line 44 "./lpsrc/flx_felix_tangler.pak"
NOTEQUAL = 139
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSEQUAL = 140
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATEREQUAL = 141
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFT = 142
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFT = 143
#line 44 "./lpsrc/flx_felix_tangler.pak"
STARSTAR = 144
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSCOLON = 145
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONGREATER = 146
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOT = 147
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONCOLON = 148
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSPLUS = 149
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSMINUS = 150
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSEQUAL = 151
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSEQUAL = 152
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAREQUAL = 153
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASHEQUAL = 154
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENTEQUAL = 155
#line 44 "./lpsrc/flx_felix_tangler.pak"
CARETEQUAL = 156
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAREQUAL = 157
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPEREQUAL = 158
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDEEQUAL = 159
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONEQUAL = 160
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTARROW = 161
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQRIGHTARROW = 162
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTARROW = 163
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQANGLE = 164
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQANGLE = 165
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQBAR = 166
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQBAR = 167
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPERAMPER = 168
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBARVBAR = 169
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHAMPER = 170
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHVBAR = 171
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHCIRCUMFLEX = 172
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANG = 173
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFTEQUAL = 174
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFTEQUAL = 175
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTRIGHTARROW = 176
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDEQEQUAL = 177
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDNOTEQUAL = 178
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESSEQUAL = 179
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATEREQUAL = 180
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOTDOT = 181
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTRIGHTARROW = 182
#line 44 "./lpsrc/flx_felix_tangler.pak"
LONGRIGHTARROW = 183
#line 44 "./lpsrc/flx_felix_tangler.pak"
PARSE_ACTION = 184
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANGSLASH = 185
#line 44 "./lpsrc/flx_felix_tangler.pak"
N_TOKENS = 186
#--end constants--

tok_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        tok_name[_value] = _name


