#! /usr/bin/python2.4
#line 24 "./lpsrc/flx_felix_tangler.pak"

#--start constants--
ENDMARKER = 0
NAME = 1
NUMBER = 2
STRING = 3
NEWLINE = 4
INDENT = 5
DEDENT = 6
ERRORTOKEN = 7
OP = 8
#line 40 "./lpsrc/flx_felix_tangler.pak"
ALL = 9
#line 40 "./lpsrc/flx_felix_tangler.pak"
ASSERT = 10
#line 40 "./lpsrc/flx_felix_tangler.pak"
AXIOM = 11
#line 40 "./lpsrc/flx_felix_tangler.pak"
BODY = 12
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALL = 13
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASE = 14
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASENO = 15
#line 40 "./lpsrc/flx_felix_tangler.pak"
CLASS = 16
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMMENT_KEYWORD = 17
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMPOUND = 18
#line 40 "./lpsrc/flx_felix_tangler.pak"
CONST = 19
#line 40 "./lpsrc/flx_felix_tangler.pak"
CCLASS = 20
#line 40 "./lpsrc/flx_felix_tangler.pak"
CSTRUCT = 21
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTOR = 22
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTYPES = 23
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEF = 24
#line 40 "./lpsrc/flx_felix_tangler.pak"
DO = 25
#line 40 "./lpsrc/flx_felix_tangler.pak"
DONE = 26
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELIF = 27
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELSE = 28
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDIF = 29
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDMATCH = 30
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENUM = 31
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPECT = 32
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPORT = 33
#line 40 "./lpsrc/flx_felix_tangler.pak"
FOR = 34
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORGET = 35
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORK = 36
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTOR = 37
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTION = 38
#line 40 "./lpsrc/flx_felix_tangler.pak"
GOTO = 39
#line 40 "./lpsrc/flx_felix_tangler.pak"
HEADER = 40
#line 40 "./lpsrc/flx_felix_tangler.pak"
IDENT = 41
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCLUDE = 42
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCOMPLETE = 43
#line 40 "./lpsrc/flx_felix_tangler.pak"
INF = 44
#line 40 "./lpsrc/flx_felix_tangler.pak"
IN = 45
#line 40 "./lpsrc/flx_felix_tangler.pak"
IS = 46
#line 40 "./lpsrc/flx_felix_tangler.pak"
INHERIT = 47
#line 40 "./lpsrc/flx_felix_tangler.pak"
INLINE = 48
#line 40 "./lpsrc/flx_felix_tangler.pak"
JUMP = 49
#line 40 "./lpsrc/flx_felix_tangler.pak"
LET = 50
#line 40 "./lpsrc/flx_felix_tangler.pak"
LOOP = 51
#line 40 "./lpsrc/flx_felix_tangler.pak"
LVAL = 52
#line 40 "./lpsrc/flx_felix_tangler.pak"
MACRO = 53
#line 40 "./lpsrc/flx_felix_tangler.pak"
MODULE = 54
#line 40 "./lpsrc/flx_felix_tangler.pak"
NAN = 55
#line 40 "./lpsrc/flx_felix_tangler.pak"
NEW = 56
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOINLINE = 57
#line 40 "./lpsrc/flx_felix_tangler.pak"
NONTERM = 58
#line 40 "./lpsrc/flx_felix_tangler.pak"
NORETURN = 59
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOT = 60
#line 40 "./lpsrc/flx_felix_tangler.pak"
OBJECT = 61
#line 40 "./lpsrc/flx_felix_tangler.pak"
OPEN = 62
#line 40 "./lpsrc/flx_felix_tangler.pak"
PACKAGE = 63
#line 40 "./lpsrc/flx_felix_tangler.pak"
POD = 64
#line 40 "./lpsrc/flx_felix_tangler.pak"
PRIVATE = 65
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROCEDURE = 66
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROPERTY = 67
#line 40 "./lpsrc/flx_felix_tangler.pak"
REDUCE = 68
#line 40 "./lpsrc/flx_felix_tangler.pak"
REF = 69
#line 40 "./lpsrc/flx_felix_tangler.pak"
RENAME = 70
#line 40 "./lpsrc/flx_felix_tangler.pak"
REQUIRES = 71
#line 40 "./lpsrc/flx_felix_tangler.pak"
RETURN = 72
#line 40 "./lpsrc/flx_felix_tangler.pak"
STRUCT = 73
#line 40 "./lpsrc/flx_felix_tangler.pak"
THEN = 74
#line 40 "./lpsrc/flx_felix_tangler.pak"
TODO = 75
#line 40 "./lpsrc/flx_felix_tangler.pak"
TO = 76
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEDEF = 77
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPE = 78
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNION = 79
#line 40 "./lpsrc/flx_felix_tangler.pak"
USE = 80
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAL = 81
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAR = 82
#line 40 "./lpsrc/flx_felix_tangler.pak"
WHEN = 83
#line 40 "./lpsrc/flx_felix_tangler.pak"
WITH = 84
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNDERSCORE = 85
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_POINTER = 86
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_TYPE = 87
#line 40 "./lpsrc/flx_felix_tangler.pak"
SVC = 88
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEREF = 89
#line 40 "./lpsrc/flx_felix_tangler.pak"
AND = 90
#line 40 "./lpsrc/flx_felix_tangler.pak"
AS = 91
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALLBACK = 92
#line 40 "./lpsrc/flx_felix_tangler.pak"
CODE = 93
#line 40 "./lpsrc/flx_felix_tangler.pak"
IF = 94
#line 40 "./lpsrc/flx_felix_tangler.pak"
ISIN = 95
#line 40 "./lpsrc/flx_felix_tangler.pak"
MATCH = 96
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOEXPAND = 97
#line 40 "./lpsrc/flx_felix_tangler.pak"
OF = 98
#line 40 "./lpsrc/flx_felix_tangler.pak"
OR = 99
#line 40 "./lpsrc/flx_felix_tangler.pak"
PARSE = 100
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGEXP = 101
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGLEX = 102
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGMATCH = 103
#line 40 "./lpsrc/flx_felix_tangler.pak"
THE = 104
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEMATCH = 105
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOLLAR = 106
#line 44 "./lpsrc/flx_felix_tangler.pak"
QUEST = 107
#line 44 "./lpsrc/flx_felix_tangler.pak"
EXCLAMATION = 108
#line 44 "./lpsrc/flx_felix_tangler.pak"
LPAR = 109
#line 44 "./lpsrc/flx_felix_tangler.pak"
RPAR = 110
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQB = 111
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQB = 112
#line 44 "./lpsrc/flx_felix_tangler.pak"
LBRACE = 113
#line 44 "./lpsrc/flx_felix_tangler.pak"
RBRACE = 114
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLON = 115
#line 44 "./lpsrc/flx_felix_tangler.pak"
COMMA = 116
#line 44 "./lpsrc/flx_felix_tangler.pak"
SEMI = 117
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUS = 118
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUS = 119
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAR = 120
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASH = 121
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAR = 122
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPER = 123
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESS = 124
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATER = 125
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQUAL = 126
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOT = 127
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENT = 128
#line 44 "./lpsrc/flx_felix_tangler.pak"
BACKQUOTE = 129
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDE = 130
#line 44 "./lpsrc/flx_felix_tangler.pak"
CIRCUMFLEX = 131
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASH = 132
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESS = 133
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATER = 134
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQEQUAL = 135
#line 44 "./lpsrc/flx_felix_tangler.pak"
NOTEQUAL = 136
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSEQUAL = 137
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATEREQUAL = 138
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFT = 139
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFT = 140
#line 44 "./lpsrc/flx_felix_tangler.pak"
STARSTAR = 141
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSCOLON = 142
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONGREATER = 143
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOT = 144
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONCOLON = 145
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSPLUS = 146
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSMINUS = 147
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSEQUAL = 148
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSEQUAL = 149
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAREQUAL = 150
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASHEQUAL = 151
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENTEQUAL = 152
#line 44 "./lpsrc/flx_felix_tangler.pak"
CARETEQUAL = 153
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAREQUAL = 154
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPEREQUAL = 155
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDEEQUAL = 156
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONEQUAL = 157
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTARROW = 158
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQRIGHTARROW = 159
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTARROW = 160
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQANGLE = 161
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQANGLE = 162
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQBAR = 163
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQBAR = 164
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPERAMPER = 165
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBARVBAR = 166
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHAMPER = 167
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHVBAR = 168
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHCIRCUMFLEX = 169
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANG = 170
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFTEQUAL = 171
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFTEQUAL = 172
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTRIGHTARROW = 173
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDEQEQUAL = 174
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDNOTEQUAL = 175
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESSEQUAL = 176
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATEREQUAL = 177
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOTDOT = 178
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTRIGHTARROW = 179
#line 44 "./lpsrc/flx_felix_tangler.pak"
LONGRIGHTARROW = 180
#line 44 "./lpsrc/flx_felix_tangler.pak"
PARSE_ACTION = 181
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANGSLASH = 182
#line 44 "./lpsrc/flx_felix_tangler.pak"
N_TOKENS = 183
#--end constants--

tok_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        tok_name[_value] = _name


