#! /usr/bin/python2.4
#line 24 "./lpsrc/flx_felix_tangler.pak"

#--start constants--
ENDMARKER = 0
NAME = 1
NUMBER = 2
STRING = 3
NEWLINE = 4
INDENT = 5
DEDENT = 6
ERRORTOKEN = 7
OP = 8
#line 40 "./lpsrc/flx_felix_tangler.pak"
ALL = 9
#line 40 "./lpsrc/flx_felix_tangler.pak"
ASSERT = 10
#line 40 "./lpsrc/flx_felix_tangler.pak"
AXIOM = 11
#line 40 "./lpsrc/flx_felix_tangler.pak"
BODY = 12
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALL = 13
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASE = 14
#line 40 "./lpsrc/flx_felix_tangler.pak"
CASENO = 15
#line 40 "./lpsrc/flx_felix_tangler.pak"
CLASS = 16
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMMENT_KEYWORD = 17
#line 40 "./lpsrc/flx_felix_tangler.pak"
COMPOUND = 18
#line 40 "./lpsrc/flx_felix_tangler.pak"
CONST = 19
#line 40 "./lpsrc/flx_felix_tangler.pak"
CCLASS = 20
#line 40 "./lpsrc/flx_felix_tangler.pak"
CSTRUCT = 21
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTOR = 22
#line 40 "./lpsrc/flx_felix_tangler.pak"
CTYPES = 23
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEF = 24
#line 40 "./lpsrc/flx_felix_tangler.pak"
DO = 25
#line 40 "./lpsrc/flx_felix_tangler.pak"
DONE = 26
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELIF = 27
#line 40 "./lpsrc/flx_felix_tangler.pak"
ELSE = 28
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDCASE = 29
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDIF = 30
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENDMATCH = 31
#line 40 "./lpsrc/flx_felix_tangler.pak"
ENUM = 32
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPECT = 33
#line 40 "./lpsrc/flx_felix_tangler.pak"
EXPORT = 34
#line 40 "./lpsrc/flx_felix_tangler.pak"
FOR = 35
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORGET = 36
#line 40 "./lpsrc/flx_felix_tangler.pak"
FORK = 37
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTOR = 38
#line 40 "./lpsrc/flx_felix_tangler.pak"
FUNCTION = 39
#line 40 "./lpsrc/flx_felix_tangler.pak"
GENERATOR = 40
#line 40 "./lpsrc/flx_felix_tangler.pak"
GOTO = 41
#line 40 "./lpsrc/flx_felix_tangler.pak"
HEADER = 42
#line 40 "./lpsrc/flx_felix_tangler.pak"
IDENT = 43
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCLUDE = 44
#line 40 "./lpsrc/flx_felix_tangler.pak"
INCOMPLETE = 45
#line 40 "./lpsrc/flx_felix_tangler.pak"
INF = 46
#line 40 "./lpsrc/flx_felix_tangler.pak"
IN = 47
#line 40 "./lpsrc/flx_felix_tangler.pak"
INSTANCE = 48
#line 40 "./lpsrc/flx_felix_tangler.pak"
IS = 49
#line 40 "./lpsrc/flx_felix_tangler.pak"
INHERIT = 50
#line 40 "./lpsrc/flx_felix_tangler.pak"
INLINE = 51
#line 40 "./lpsrc/flx_felix_tangler.pak"
JUMP = 52
#line 40 "./lpsrc/flx_felix_tangler.pak"
LET = 53
#line 40 "./lpsrc/flx_felix_tangler.pak"
LOOP = 54
#line 40 "./lpsrc/flx_felix_tangler.pak"
LVAL = 55
#line 40 "./lpsrc/flx_felix_tangler.pak"
MACRO = 56
#line 40 "./lpsrc/flx_felix_tangler.pak"
MODULE = 57
#line 40 "./lpsrc/flx_felix_tangler.pak"
NAN = 58
#line 40 "./lpsrc/flx_felix_tangler.pak"
NEW = 59
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOINLINE = 60
#line 40 "./lpsrc/flx_felix_tangler.pak"
NONTERM = 61
#line 40 "./lpsrc/flx_felix_tangler.pak"
NORETURN = 62
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOT = 63
#line 40 "./lpsrc/flx_felix_tangler.pak"
OBJECT = 64
#line 40 "./lpsrc/flx_felix_tangler.pak"
OPEN = 65
#line 40 "./lpsrc/flx_felix_tangler.pak"
PACKAGE = 66
#line 40 "./lpsrc/flx_felix_tangler.pak"
POD = 67
#line 40 "./lpsrc/flx_felix_tangler.pak"
PRIVATE = 68
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROCEDURE = 69
#line 40 "./lpsrc/flx_felix_tangler.pak"
PROPERTY = 70
#line 40 "./lpsrc/flx_felix_tangler.pak"
REDUCE = 71
#line 40 "./lpsrc/flx_felix_tangler.pak"
REF = 72
#line 40 "./lpsrc/flx_felix_tangler.pak"
RENAME = 73
#line 40 "./lpsrc/flx_felix_tangler.pak"
REQUIRES = 74
#line 40 "./lpsrc/flx_felix_tangler.pak"
RETURN = 75
#line 40 "./lpsrc/flx_felix_tangler.pak"
STRUCT = 76
#line 40 "./lpsrc/flx_felix_tangler.pak"
THEN = 77
#line 40 "./lpsrc/flx_felix_tangler.pak"
TODO = 78
#line 40 "./lpsrc/flx_felix_tangler.pak"
TO = 79
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEDEF = 80
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPE = 81
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPECLASS = 82
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNION = 83
#line 40 "./lpsrc/flx_felix_tangler.pak"
USE = 84
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAL = 85
#line 40 "./lpsrc/flx_felix_tangler.pak"
VAR = 86
#line 40 "./lpsrc/flx_felix_tangler.pak"
WHEN = 87
#line 40 "./lpsrc/flx_felix_tangler.pak"
WITH = 88
#line 40 "./lpsrc/flx_felix_tangler.pak"
YIELD = 89
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_POINTER = 90
#line 40 "./lpsrc/flx_felix_tangler.pak"
GC_TYPE = 91
#line 40 "./lpsrc/flx_felix_tangler.pak"
SVC = 92
#line 40 "./lpsrc/flx_felix_tangler.pak"
DEREF = 93
#line 40 "./lpsrc/flx_felix_tangler.pak"
AND = 94
#line 40 "./lpsrc/flx_felix_tangler.pak"
AS = 95
#line 40 "./lpsrc/flx_felix_tangler.pak"
CALLBACK = 96
#line 40 "./lpsrc/flx_felix_tangler.pak"
CODE = 97
#line 40 "./lpsrc/flx_felix_tangler.pak"
IF = 98
#line 40 "./lpsrc/flx_felix_tangler.pak"
ISIN = 99
#line 40 "./lpsrc/flx_felix_tangler.pak"
MATCH = 100
#line 40 "./lpsrc/flx_felix_tangler.pak"
NOEXPAND = 101
#line 40 "./lpsrc/flx_felix_tangler.pak"
OF = 102
#line 40 "./lpsrc/flx_felix_tangler.pak"
OR = 103
#line 40 "./lpsrc/flx_felix_tangler.pak"
PARSE = 104
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGEXP = 105
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGLEX = 106
#line 40 "./lpsrc/flx_felix_tangler.pak"
REGMATCH = 107
#line 40 "./lpsrc/flx_felix_tangler.pak"
THE = 108
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPEMATCH = 109
#line 40 "./lpsrc/flx_felix_tangler.pak"
TYPECASE = 110
#line 40 "./lpsrc/flx_felix_tangler.pak"
UNDERSCORE = 111
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOLLAR = 112
#line 44 "./lpsrc/flx_felix_tangler.pak"
QUEST = 113
#line 44 "./lpsrc/flx_felix_tangler.pak"
EXCLAMATION = 114
#line 44 "./lpsrc/flx_felix_tangler.pak"
LPAR = 115
#line 44 "./lpsrc/flx_felix_tangler.pak"
RPAR = 116
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQB = 117
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQB = 118
#line 44 "./lpsrc/flx_felix_tangler.pak"
LBRACE = 119
#line 44 "./lpsrc/flx_felix_tangler.pak"
RBRACE = 120
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLON = 121
#line 44 "./lpsrc/flx_felix_tangler.pak"
COMMA = 122
#line 44 "./lpsrc/flx_felix_tangler.pak"
SEMI = 123
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUS = 124
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUS = 125
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAR = 126
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASH = 127
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAR = 128
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPER = 129
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESS = 130
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATER = 131
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQUAL = 132
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOT = 133
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENT = 134
#line 44 "./lpsrc/flx_felix_tangler.pak"
BACKQUOTE = 135
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDE = 136
#line 44 "./lpsrc/flx_felix_tangler.pak"
CIRCUMFLEX = 137
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASH = 138
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESS = 139
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATER = 140
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQEQUAL = 141
#line 44 "./lpsrc/flx_felix_tangler.pak"
NOTEQUAL = 142
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSEQUAL = 143
#line 44 "./lpsrc/flx_felix_tangler.pak"
GREATEREQUAL = 144
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFT = 145
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFT = 146
#line 44 "./lpsrc/flx_felix_tangler.pak"
STARSTAR = 147
#line 44 "./lpsrc/flx_felix_tangler.pak"
LESSCOLON = 148
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONGREATER = 149
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOT = 150
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONCOLON = 151
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSPLUS = 152
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSMINUS = 153
#line 44 "./lpsrc/flx_felix_tangler.pak"
PLUSEQUAL = 154
#line 44 "./lpsrc/flx_felix_tangler.pak"
MINUSEQUAL = 155
#line 44 "./lpsrc/flx_felix_tangler.pak"
STAREQUAL = 156
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLASHEQUAL = 157
#line 44 "./lpsrc/flx_felix_tangler.pak"
PERCENTEQUAL = 158
#line 44 "./lpsrc/flx_felix_tangler.pak"
CARETEQUAL = 159
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBAREQUAL = 160
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPEREQUAL = 161
#line 44 "./lpsrc/flx_felix_tangler.pak"
TILDEEQUAL = 162
#line 44 "./lpsrc/flx_felix_tangler.pak"
COLONEQUAL = 163
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTARROW = 164
#line 44 "./lpsrc/flx_felix_tangler.pak"
EQRIGHTARROW = 165
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTARROW = 166
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQANGLE = 167
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQANGLE = 168
#line 44 "./lpsrc/flx_felix_tangler.pak"
LSQBAR = 169
#line 44 "./lpsrc/flx_felix_tangler.pak"
RSQBAR = 170
#line 44 "./lpsrc/flx_felix_tangler.pak"
AMPERAMPER = 171
#line 44 "./lpsrc/flx_felix_tangler.pak"
VBARVBAR = 172
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHAMPER = 173
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHVBAR = 174
#line 44 "./lpsrc/flx_felix_tangler.pak"
SLOSHCIRCUMFLEX = 175
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANG = 176
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTSHIFTEQUAL = 177
#line 44 "./lpsrc/flx_felix_tangler.pak"
RIGHTSHIFTEQUAL = 178
#line 44 "./lpsrc/flx_felix_tangler.pak"
LEFTRIGHTARROW = 179
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDEQEQUAL = 180
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDNOTEQUAL = 181
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDLESSEQUAL = 182
#line 44 "./lpsrc/flx_felix_tangler.pak"
ANDGREATEREQUAL = 183
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTDOTDOT = 184
#line 44 "./lpsrc/flx_felix_tangler.pak"
DOTRIGHTARROW = 185
#line 44 "./lpsrc/flx_felix_tangler.pak"
LONGRIGHTARROW = 186
#line 44 "./lpsrc/flx_felix_tangler.pak"
PARSE_ACTION = 187
#line 44 "./lpsrc/flx_felix_tangler.pak"
HASHBANGSLASH = 188
#line 44 "./lpsrc/flx_felix_tangler.pak"
N_TOKENS = 189
#--end constants--

tok_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        tok_name[_value] = _name


