open Flx_token

let string_of_string s = "\"" ^  Flx_string.c_quote_of_string s ^ "\""

let sp p = match p with
  | `No_prio -> ""
  | `Eq_prio p -> "[="^p^"]"
  | `Less_prio p -> "[<"^p^"]"
  | `Lesseq_prio p -> "[<="^p^"]"
  | `Greater_prio p -> "[>"^p^"]"
  | `Greatereq_prio p -> "[>="^p^"]"

let string_of_token = function
  | DUMMY -> "DUMMY"
  | NAME s -> s
  | NONTERMINAL (s,p) -> s ^ sp p
  | STRING s -> Flx_string.c_quote_of_string s
  | REGEX r  -> "(some regex here ..)"
  | QUEST _ -> "?"
  | LPAR _ -> "("
  | RPAR _ -> ")"
  | LSQB _ -> "["
  | RSQB _ -> "]"
  | LBRACE _ -> "{"
  | RBRACE _ -> "}"
  | COMMA _ -> ","
  | PLUS _ -> "+"
  | STAR _ -> "*"
  | VBAR _ -> "|"
  | LESS _ -> "<"
  | GREATER _ -> ">"
  | EQUAL _ -> "="
  | EQEQUAL _ -> "=="
  | NOTEQUAL _ -> "!="
  | LESSEQUAL _ -> "<="
  | GREATEREQUAL _ -> ">="
  | UNDERSCORE _ -> "_"
  | NEWLINE -> "<NEWLINE>"
  | ENDMARKER -> "<<EOF>>"
  | ERRORTOKEN s -> "<<ERROR '"^ s ^"'>>"
  | SLOSH -> "\\"

let name_of_token = function
  | DUMMY -> "DUMMY"
  | NAME _ -> "NAME"
  | NONTERMINAL _ -> "NONTERMINAL"
  | STRING _ -> "STRING"
  | REGEX _ -> "REGEX"
  | QUEST _ -> "QUEST"
  | LPAR -> "LPAR"
  | RPAR -> "RPAR"
  | LSQB -> "LSQB"
  | RSQB -> "RSQB"
  | LBRACE -> "LBRACE"
  | RBRACE -> "RBRACE"
  | COMMA -> "COMMA"
  | PLUS -> "PLUS"
  | STAR -> "STAR"
  | VBAR -> "VBAR"
  | LESS -> "LESS"
  | GREATER -> "GREATER"
  | EQUAL -> "EQUAL"
  | EQEQUAL -> "EQEQUAL"
  | NOTEQUAL -> "NOTEQUAL"
  | LESSEQUAL -> "LESSEQUAL"
  | GREATEREQUAL -> "GREATEREQUAL"
  | UNDERSCORE -> "UNDERSCORE"
  | NEWLINE -> "NEWLINE"
  | ENDMARKER -> "ENDMARKER"
  | ERRORTOKEN _ -> "ERRORTOKEN"
  | SLOSH -> "SLOSH"

