# define BISON_GRAMPAR_TAB_H     /* tweak */
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
# define        TOK_INTEGER     257
# define        TOK_NAME        258
# define        TOK_STRING      259
# define        TOK_LIT_CODE    260
# define        TOK_LBRACE      261
# define        TOK_RBRACE      262
# define        TOK_COLON       263
# define        TOK_SEMICOLON   264
# define        TOK_ARROW       265
# define        TOK_LPAREN      266
# define        TOK_RPAREN      267
# define        TOK_COMMA       268
# define        TOK_TERMINALS   269
# define        TOK_TOKEN       270
# define        TOK_NONTERM     271
# define        TOK_FUN 272
# define        TOK_VERBATIM    273
# define        TOK_IMPL_VERBATIM       274
# define        TOK_PRECEDENCE  275
# define        TOK_OPTION      276
# define        TOK_EXPECT      277
# define        TOK_CONTEXT_CLASS       278
# define        TOK_SUBSETS     279
