#! /bin/bash
### BEGIN INIT INFO
# Provides:          webserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop/restart Felix webserver
# Description:       Start/stop/restart Felix webserver
#                    
### END INIT INFO

#Adapted from script provided by "Erick Tryzelaar <erick.tryzelaar@gmail.com>"

PROG="webserver"
PROG_PATH="/home/fletch/project/felix/build/release/host/bin"
PROG_ARGS="--port=80 --root=/home/fletch/project/felix/build/release/" 
PID_PATH="/var/run/"
export LD_LIBRARY_PATH=/home/fletch/project/felix/build/release/host/lib/rtl

start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
            $PROG_PATH/$PROG $PROG_ARGS 2>&1 >/var/log/$PROG &
        echo "Felix webserver started"
        touch "$PID_PATH/$PROG.pid"
    fi
}

stop() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        killall $PROG
        rm "$PID_PATH/$PROG.pid"
        echo "Felix webserver stopped"
    else
        echo "Error! Felix webserver not started!" 1>&2
        exit 1
    fi
}

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac
