name: felix
run-name: ${{ github.actor }} test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TEST RUN"
      - run: git clone -b 4.14 https://github.com/ocaml/ocaml.git
      - run: cd ocaml; ./configure
      - run: cd ocaml; make; make install
      - run: ocaml --version


