name: felix
run-name: ${{ github.actor }} test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $PATH
      - run: git clone -b 4.14 https://github.com/ocaml/ocaml.git
      - run: cd ocaml; ./configure
      - run: cd ocaml; make
      - run: cd ocaml; sudo make install
      - run: ocaml --version
      - run: python3 --version
      - run: g++ --version
      - run: ls
      - run: export FLX_SHELL_ECHO=1
      - run: export FLX_BUILD_TOOLCHAIN_FAMILY=gcc
      - run: make


