name: felix
run-name: ${{ github.actor }} test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "TEST RUN"
      - run: echo $PATH
      - run: mkdir -p /usr/local
      - run: mkdir -p /usr/local/bin
      - run: mkdir -p /usr/local/lib
      - run: sudo mkdir -p /usr/local/lib/ocaml
      - run: git clone -b 4.14 https://github.com/ocaml/ocaml.git
      - run: cd ocaml; ./configure
      - run: cd ocaml; make
      - run: cd ocaml; make install
      - run: ocaml --version


