#!/usr/bin/env python3
from os.path import realpath, join, dirname
import sys, os

sys.path.append(realpath(join(dirname(sys.argv[0]), 'lib')))

from fbuild.main import main

# don't know why someone would need this...but oh well
if __name__ == '__main__':
    main()
