#ifndef _FLX_GUARD_mktutindex
#define _FLX_GUARD_mktutindex
//Input file: src/tools/mktutindex.flx
//Generated by Felix Version 1.1.7dev
//Timestamp: 2011/12/14 10:16:32 UTC
//Timestamp: 2011/12/14 20:16:32 (local)

//FELIX RUNTIME
#include "flx_rtl.hpp"
#include "flx_gc.hpp"
#ifndef FLX_NO_INCLUDES
#include "mktutindex.includes"
#endif


//-----------------------------------------
//USER HEADERS
#include "flx_rtl_config.hpp"
#include <string>
#include <iostream>
#include <cstdlib>
#include <errno.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/types.h>

//-----------------------------------------
//FELIX SYSTEM
namespace flxusr { namespace mktutindex {
struct thread_frame_t;

//-----------------------------------------
//NAME THE TYPES

//PRIMITIVE 5143 INSTANCE 54035: string
typedef ::std::basic_string<char> _a5143t_54035;
typedef int _us2;

//TYPE 54037: string^2
struct _at54037;

//PRIMITIVE 2523 INSTANCE 54038: int
//typedef int int;

//TYPE 54039: int^2
struct _at54039;

//PRIMITIVE 7492 INSTANCE 54040: RE2
typedef ::re2::RE2* _a7492t_54040;

//PRIMITIVE 7491 INSTANCE 54041: RE2_
typedef ::re2::RE2 _a7491t_54041;

//TYPE 54042: bool^2
struct _at54042;

//PRIMITIVE 2516 INSTANCE 54044: address
typedef void * _a2516t_54044;

//PRIMITIVE 10927 INSTANCE 54045: dirent_t
typedef struct dirent* _a10927t_54045;

//PRIMITIVE 10928 INSTANCE 54046: DIR_t
typedef DIR* _a10928t_54046;

//TYPE 54047: string * &DIR_t
struct _tt54047;

//PRIMITIVE 4319 INSTANCE 54048: ostream
typedef ::std::ostream* _a4319t_54048;

//TYPE 54049: ostream * string
struct _tt54049;

//TYPE 54051: DIR_t * dirent_t * &dirent_t * &int
struct _tt54051;

//TYPE 54052: list[string] * string
struct _tt54052;

//TYPE 54053: string * list[string]
struct _tt54053;

//TYPE 54054: string -> void
struct _pt54054;

//PRIMITIVE 4293 INSTANCE 54055: output_text_file
typedef FILE* _a4293t_54055;

//TYPE 54056: output_text_file * string
struct _tt54056;

//PRIMITIVE 4292 INSTANCE 54057: input_text_file
typedef FILE* _a4292t_54057;

//PRIMITIVE 2518 INSTANCE 54058: char
//typedef char char;

//TYPE 54059: char^2
struct _at54059;

//TYPE 54060: string * int
struct _tt54060;

//PRIMITIVE 10786 INSTANCE 54083: stat_t
typedef struct stat _a10786t_54083;

//TYPE 54084: string * &stat_t * &int
struct _tt54084;

//PRIMITIVE 10815 INSTANCE 54085: mode_t
//typedef mode_t mode_t;

//TYPE 54086: mode_t^2
struct _at54086;

//PRIMITIVE 10702 INSTANCE 54088: errno_t
typedef int _a10702t_54088;

//TYPE 54089: errno_t^2
struct _at54089;

//PRIMITIVE 7494 INSTANCE 54090: StringPiece
typedef ::re2::StringPiece _a7494t_54090;

//PRIMITIVE 7557 INSTANCE 54091: Anchor
typedef ::re2::RE2::Anchor _a7557t_54091;

//TYPE 54092: RE2 * StringPiece * int * Anchor * &StringPiece * int
struct _tt54092;

//TYPE 54093: &list[string]^2
struct _at54093;

//TYPE 54094: &list[string] * list[string]
struct _tt54094;


//-----------------------------------------
//DEFINE THE TYPES

//TYPE 54037: string^2
struct _at54037 {
  static size_t const len = 2;
  typedef _a5143t_54035 element_type;
  _a5143t_54035 data[2];
  _at54037() {}
  _at54037(_a5143t_54035 a0, _a5143t_54035 a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54039: int^2
struct _at54039 {
  static size_t const len = 2;
  typedef int element_type;
  int data[2];
  _at54039() {}
  _at54039(int a0, int a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54042: bool^2
struct _at54042 {
  static size_t const len = 2;
  typedef _us2 element_type;
  _us2 data[2];
  _at54042() {}
  _at54042(_us2 a0, _us2 a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54047: string * &DIR_t
struct _tt54047 {
  _a5143t_54035 mem_0;
  _a10928t_54046* mem_1;
  _tt54047(){}
  _tt54047(_a5143t_54035 a0, _a10928t_54046* a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54049: ostream * string
struct _tt54049 {
  _a4319t_54048 mem_0;
  _a5143t_54035 mem_1;
  _tt54049(){}
  _tt54049(_a4319t_54048 a0, _a5143t_54035 a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54051: DIR_t * dirent_t * &dirent_t * &int
struct _tt54051 {
  _a10928t_54046 mem_0;
  _a10927t_54045 mem_1;
  _a10927t_54045* mem_2;
  int* mem_3;
  _tt54051(){}
  _tt54051(_a10928t_54046 a0, _a10927t_54045 a1, _a10927t_54045* a2, int* a3):
    mem_0(a0), mem_1(a1), mem_2(a2), mem_3(a3){}
};

//TYPE 54052: list[string] * string
struct _tt54052 {
  void* mem_0;
  _a5143t_54035 mem_1;
  _tt54052(){}
  _tt54052(void* a0, _a5143t_54035 a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54053: string * list[string]
struct _tt54053 {
  _a5143t_54035 mem_0;
  void* mem_1;
  _tt54053(){}
  _tt54053(_a5143t_54035 a0, void* a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54054: string -> void
struct _pt54054: ::flx::rtl::con_t {
  typedef void rettype;
  typedef _a5143t_54035 argtype;
  virtual ::flx::rtl::con_t *call(::flx::rtl::con_t *, _a5143t_54035 const &)=0;
  virtual _pt54054 *clone()=0;
  virtual ::flx::rtl::con_t *resume()=0;
};

//TYPE 54056: output_text_file * string
struct _tt54056 {
  _a4293t_54055 mem_0;
  _a5143t_54035 mem_1;
  _tt54056(){}
  _tt54056(_a4293t_54055 a0, _a5143t_54035 a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54059: char^2
struct _at54059 {
  static size_t const len = 2;
  typedef char element_type;
  char data[2];
  _at54059() {}
  _at54059(char a0, char a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54060: string * int
struct _tt54060 {
  _a5143t_54035 mem_0;
  int mem_1;
  _tt54060(){}
  _tt54060(_a5143t_54035 a0, int a1):
    mem_0(a0), mem_1(a1){}
};

//TYPE 54084: string * &stat_t * &int
struct _tt54084 {
  _a5143t_54035 mem_0;
  _a10786t_54083* mem_1;
  int* mem_2;
  _tt54084(){}
  _tt54084(_a5143t_54035 a0, _a10786t_54083* a1, int* a2):
    mem_0(a0), mem_1(a1), mem_2(a2){}
};

//TYPE 54086: mode_t^2
struct _at54086 {
  static size_t const len = 2;
  typedef mode_t element_type;
  mode_t data[2];
  _at54086() {}
  _at54086(mode_t a0, mode_t a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54089: errno_t^2
struct _at54089 {
  static size_t const len = 2;
  typedef _a10702t_54088 element_type;
  _a10702t_54088 data[2];
  _at54089() {}
  _at54089(_a10702t_54088 a0, _a10702t_54088 a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54092: RE2 * StringPiece * int * Anchor * &StringPiece * int
struct _tt54092 {
  _a7492t_54040 mem_0;
  _a7494t_54090 mem_1;
  int mem_2;
  _a7557t_54091 mem_3;
  _a7494t_54090* mem_4;
  int mem_5;
  _tt54092(){}
  _tt54092(_a7492t_54040 a0, _a7494t_54090 a1, int a2, _a7557t_54091 a3, _a7494t_54090* a4, int a5):
    mem_0(a0), mem_1(a1), mem_2(a2), mem_3(a3), mem_4(a4), mem_5(a5){}
};

//TYPE 54093: &list[string]^2
struct _at54093 {
  static size_t const len = 2;
  typedef void** element_type;
  void** data[2];
  _at54093() {}
  _at54093(void** a0, void** a1) {
    data[0] = a0;
    data[1] = a1;
  }
};

//TYPE 54094: &list[string] * list[string]
struct _tt54094 {
  void** mem_0;
  void* mem_1;
  _tt54094(){}
  _tt54094(void** a0, void* a1):
    mem_0(a0), mem_1(a1){}
};


//-----------------------------------------
//DEFINE FUNCTION CLASS NAMES
struct _lam_10458;
struct _init_;
struct rfi;
struct _i21716_f21716__lam_10635__apos_2;
struct _i21750_f21750__lam_10635__apos_2;
struct println;
struct _i43894_f43894__lam_10635__apos_2;


//-----------------------------------------
//DEFINE FUNCTION CLASSES

//------------------------------
//FUNCTION <10989>: _lam_10458
struct _lam_10458: _pt54054 {
  FLX_FMEM_DECL

  int j;
  _us2 found;
  int i;
  int _i20631_v20631_j;
  _us2 _i20630_v20630_found;
  int _i20629_v20629_i;
  _a5143t_54035 _urv19241;
  _a5143t_54035 _urv19912;
  _a5143t_54035 hline;
  _a4292t_54057 f;
  _a5143t_54035 x;
  _lam_10458(FLX_FPAR_DECL_ONLY);
  _lam_10458* clone();
  ::flx::rtl::con_t *call(::flx::rtl::con_t*,_a5143t_54035 const &);
  ::flx::rtl::con_t *resume();
};

//------------------------------
//FUNCTION <11518>: _init_
struct _init_: ::flx::rtl::con_t {
  FLX_FMEM_DECL

  void* t;
  void* _i43939_v43939_iter__apos_2_mv_992;
  _pt54054* _f_uncurry;
  void* _i43937_v43937_x;
  void* _i43930_v43930_t;
  void* _i43929_v43929_iter__apos_2_mv_992;
  _pt54054* _i43928_v43928__f_uncurry;
  void* _i43927_v43927_x;
  void* _i22926_v22926_t;
  void* _i22925_v22925_iter__apos_2_mv_992;
  _pt54054* _i22924_v22924__f_uncurry;
  int _i22298_v22298_j;
  _us2 _i22297_v22297_found;
  int _i22296_v22296_i;
  int _i22295_v22295_j;
  _us2 _i22294_v22294_found;
  int _i22293_v22293_i;
  _a5143t_54035 _i22292_v22292__urv19241;
  _a5143t_54035 _i22291_v22291__urv19912;
  _a5143t_54035 _i22290_v22290_hline;
  _a4292t_54057 _i22289_v22289_f;
  void* _i22266_v22266_t;
  void* _i22265_v22265_iter__apos_2_mv_992;
  _pt54054* _i22264_v22264__f_uncurry;
  void* _i22263_v22263_t;
  void* _i22262_v22262_iter__apos_2_mv_992;
  _pt54054* _i22261_v22261__f_uncurry;
  _a5143t_54035 h;
  void* _i22259_v22259_t;
  void* _i22258_v22258_iter__apos_2_mv_992;
  void* _i22227_v22227_t;
  void* _i22226_v22226_iter__apos_2_mv_992;
  _pt54054* _i22225_v22225__f_uncurry;
  void* _i22157_v22157_t;
  void* _i22156_v22156_iter__apos_2_mv_992;
  _pt54054* _i22155_v22155__f_uncurry;
  void* _i22154_v22154_t;
  void* _i22153_v22153_iter__apos_2_mv_992;
  _pt54054* _i22152_v22152__f_uncurry;
  void* _i22150_v22150_t;
  void* _i22149_v22149_iter__apos_2_mv_992;
  void* acc;
  void* _i21749_v21749_aux__apos_2_mv_1004;
  void* init_uncurry;
  void* _i21747_v21747_x;
  void* _urv15948;
  _a2516t_54044 _genout_urv16016;
  void* files;
  int err;
  _a10927t_54045 eret;
  _a10927t_54045 e;
  _a10928t_54046 d;
  _a5143t_54035 _urv16240;
  void* rfi_mv_10624;
  _a5143t_54035 dname2;
  _a5143t_54035 result;
  _init_(FLX_FPAR_DECL_ONLY);
  _init_* clone();
  ::flx::rtl::con_t *call(::flx::rtl::con_t*);
  ::flx::rtl::con_t *resume();
};

//------------------------------
//PROCEDURE <21698>: _init_::rfi
struct rfi {
  FLX_FMEM_DECL
  _init_ *ptr_init_;

  void* _i21718_v21718_acc;
  void* _i21715_v21715_aux__apos_2_mv_1004;
  void* _i21714_v21714_init_uncurry;
  void* _i21713_v21713_x;
  void* _i21712_v21712__urv15948;
  void* _i21711_v21711_files;
  _a2516t_54044 _i21710_v21710__genout_urv16016;
  void* _i21709_v21709_files;
  int _i21708_v21708_err;
  _a10927t_54045 _i21707_v21707_eret;
  _a10927t_54045 _i21706_v21706_e;
  _a10928t_54046 _i21705_v21705_d;
  _a5143t_54035 _i21704_v21704__urv16240;
  void* _i21703_v21703_rfi_mv_10624;
  _us2 rfi_mv_10614;
  _a5143t_54035 _i21699_v21699_dname2;
  rfi  (FLX_FPAR_DECL _init_*);
  void* apply(_a5143t_54035 const &);
};

//------------------------------
//PROCEDURE <21716>: _init_::rfi::_lam_10635'2
struct _i21716_f21716__lam_10635__apos_2 {
  FLX_FMEM_DECL
  rfi *ptrrfi;
  _init_ *ptr_init_;

  void* _i21736_v21736_aux__apos_2_mv_982;
  void* x_uncurry;
  void* y;
  void* _urv13411;
  _us2 _urv13435;
  void* last;
  void* z;
  _us2 _genout_urv13499;
  int _i21728_v21728__lam_10635__apos_2_mv_10660;
  mode_t m;
  int _i21725_v21725_err;
  _a10786t_54083 b;
  _a5143t_54035 _urv13878;
  int _i21722_v21722__lam_10635__apos_2_mv_10653;
  _a5143t_54035 _i21721_v21721_d;
  _a5143t_54035 _i21720_v21720__lam_10635__apos_2_mv_10646;
  _a5143t_54035 _i21717_v21717_f;
  _i21716_f21716__lam_10635__apos_2  (FLX_FPAR_DECL rfi*, _init_*);
  void* apply(_a5143t_54035 const &);
};

//------------------------------
//PROCEDURE <21750>: _init_::_lam_10635'2
struct _i21750_f21750__lam_10635__apos_2 {
  FLX_FMEM_DECL
  _init_ *ptr_init_;

  void* _i43896_v43896_acc;
  void* _i43893_v43893_aux__apos_2_mv_1004;
  void* _i43892_v43892_init_uncurry;
  void* _i43891_v43891_x;
  void* _i43890_v43890__urv15948;
  _a2516t_54044 _i43888_v43888__genout_urv16016;
  void* _i43887_v43887_files;
  int _i43886_v43886_err;
  _a10927t_54045 _i43885_v43885_eret;
  _a10927t_54045 _i43884_v43884_e;
  _a10928t_54046 _i43883_v43883_d;
  _a5143t_54035 _i43882_v43882__urv16240;
  void* _i43881_v43881_rfi_mv_10624;
  _a5143t_54035 _i43879_v43879_dname2;
  void* _i21770_v21770_aux__apos_2_mv_982;
  void* _i21769_v21769_x_uncurry;
  void* _i21768_v21768_y;
  void* _i21767_v21767__urv13411;
  _us2 _i21766_v21766__urv13435;
  void* _i21765_v21765_last;
  void* _i21764_v21764_z;
  _us2 _i21763_v21763__genout_urv13499;
  int _i21762_v21762__lam_10635__apos_2_mv_10660;
  mode_t _i21760_v21760_m;
  int _i21759_v21759_err;
  _a10786t_54083 _i21758_v21758_b;
  _a5143t_54035 _i21757_v21757__urv13878;
  int _i21756_v21756__lam_10635__apos_2_mv_10653;
  _a5143t_54035 _i21755_v21755_d;
  _a5143t_54035 _i21754_v21754__lam_10635__apos_2_mv_10646;
  _a5143t_54035 _i21751_v21751_f;
  _i21750_f21750__lam_10635__apos_2  (FLX_FPAR_DECL _init_*);
  void* apply(_a5143t_54035 const &);
};

//------------------------------
//FUNCTION <41355>: println
struct println: _pt54054 {
  FLX_FMEM_DECL

  _a5143t_54035 _i41384_v41384_x;
  println(FLX_FPAR_DECL_ONLY);
  println* clone();
  ::flx::rtl::con_t *call(::flx::rtl::con_t*,_a5143t_54035 const &);
  ::flx::rtl::con_t *resume();
};

//------------------------------
//PURE C PROCEDURE <41390>: add
void* FLX_REGPARM add(FLX_FPAR_DECL  void*, _a5143t_54035);

//------------------------------
//PROCEDURE <43894>: _init_::_lam_10635'2::_lam_10635'2
struct _i43894_f43894__lam_10635__apos_2 {
  FLX_FMEM_DECL
  _i21750_f21750__lam_10635__apos_2 *ptr_i21750_f21750__lam_10635__apos_2;
  _init_ *ptr_init_;

  void* _i43912_v43912_aux__apos_2_mv_982;
  void* _i43911_v43911_x_uncurry;
  void* _i43910_v43910_y;
  void* _i43909_v43909__urv13411;
  _us2 _i43908_v43908__urv13435;
  void* _i43907_v43907_last;
  void* _i43906_v43906_z;
  _us2 _i43905_v43905__genout_urv13499;
  int _i43904_v43904__lam_10635__apos_2_mv_10660;
  mode_t _i43903_v43903_m;
  int _i43902_v43902_err;
  _a10786t_54083 _i43901_v43901_b;
  _a5143t_54035 _i43900_v43900__urv13878;
  int _i43899_v43899__lam_10635__apos_2_mv_10653;
  _a5143t_54035 _i43898_v43898_d;
  _a5143t_54035 _i43897_v43897__lam_10635__apos_2_mv_10646;
  _a5143t_54035 _i43895_v43895_f;
  _i43894_f43894__lam_10635__apos_2  (FLX_FPAR_DECL _i21750_f21750__lam_10635__apos_2*, _init_*);
  void* apply(_a5143t_54035 const &);
};

struct thread_frame_t {
  int argc;
  char **argv;
  FILE *flx_stdin;
  FILE *flx_stdout;
  FILE *flx_stderr;
  ::flx::gc::generic::gc_profile_t *gcp;
  ::flx::gc::generic::gc_shape_t *shape_list_head;
  thread_frame_t(
  );
  _a5143t_54035 INSTALL_ROOT_TOPDIR;
  _a5143t_54035 sep;
  _a4293t_54055 _i10988_v10988_f;
  void* docs;
  _a7492t_54040 re;

};

FLX_DCL_THREAD_FRAME

}} // namespace flxusr::mktutindex
using namespace ::flxusr::mktutindex;
//header complete
#endif
